TRANSLATIONS = {
    "uz": {
        "welcome": "👋 Assalomu alaykum! Yuk tashish botimizga xush kelibsiz.\nIltimos, davom etish uchun tilni tanlang:",
        "cancel_hint": "\n\n🚫 Bekor qilish uchun /cancel buyrug'ini yuboring.",
        "ask_fullname": "👤 Iltimos, Ism va Familiyangizni kiriting:",
        "invalid_fullname": "⚠️ Iltimos, to'liq ism va familiyangizni kiriting (kamida 3 ta belgi).",
        "btn_send_phone": "📱 Telefon raqamni yuborish",
        "ask_phone": "📞 Pastdagi tugmani bosib telefon raqamingizni yuboring (yoki qo'lda yozing):",
        "invalid_phone": "⚠️ Telefon raqam noto'g'ri formatda. Masalan: +998901234567\nYoki pastdagi tugmani bosib yuboring.",
        "btn_uzb": "🇺🇿 O'zbekiston",
        "ask_region": "🌍 Davlatni tanlang (yoki kiriting):",
        "btn_tashkent_city": "📍 Toshkent shahri",
        "btn_tashkent_region": "📍 Toshkent viloyati",
        "ask_district": "🏙 Viloyat yoki shaharni tanlang:",
        "districts": ["Sergeli", "Yunusobod", "Chilonzor", "Mirzo Ulug'bek", "Yashnobod", "Olmazor"],
        "ask_district_detailed": "🗺 Tumanni tanlang:",
        "btn_location_a": "📍 Hozirgi joylashuvni yuborish (A nuqta)",
        "ask_location_a": "🚚 <b>A Nuqta:</b> Yuk qayerdan olinadi? Pastdagi tugma orqali lokatsiyangizni yuboring:",
        "btn_location_b": "📍 Boradigan manzil lokatsiyasi (B nuqta)",
        "ask_location_b": "🏁 <b>B Nuqta:</b> Yuk qayerga olib boriladi? Pastdagi tugmani bosib, lokatsiyani yuboring:",
        "invalid_location": "⚠️ Iltimos, faqat lokatsiya tugmasini bosib yuboring.",
        "truck_gazelle": "🚛 Gazelle (Mebel va katta yuklar)",
        "truck_labo": "🚙 Labo / Damas (Kichik yuklar)",
        "truck_isuzu": "🚚 Isuzu (Juda katta ko'chishlar)",
        "ask_truck": "📦 Qanday turdagi yuk mashinasi kerak?",
        "movers_yes": "🙋‍♂️ Ha, yuk tashuvchilar kerak",
        "movers_no": "❌ Yo'q, o'zimiz yuklaymiz",
        "ask_movers": "💪 Sizga mebellarni ko'chirish uchun yuk tashuvchi xizmatchilar (Gruchik) kerakmi?",
        "btn_no_photo": "⏩ Rasmsiz yuborish",
        "ask_photo": "📸 Agar imkoni bo'lsa, ko'chirilishi kerak bo'lgan mebel yoki yuklar rasmini yuboring.\nYoki pastdagi tugmani bosing:",
        "success": "✅ Rahmat! Arizangiz muvaffaqiyatli qabul qilindi. Tez orada adminlarimiz siz bilan bog'lanishadi.",
        "cancel_success": "❌ Buyurtma bekor qilindi. Qaytadan boshlash uchun /start buyrug'ini yuboring.",
        "cancel_empty": "Hozir bekor qilinadigan jarayon yo'q.",
        "fallback": "🤖 Buyurtma berishni boshlash uchun /start buyrug'ini yuboring."
    },
    "ru": {
        "welcome": "👋 Добро пожаловать! Выберите язык:",
        "cancel_hint": "\n\n🚫 Отправьте команду /cancel для отмены.",
        "ask_fullname": "👤 Пожалуйста, введите ваше Имя и Фамилию:",
        "invalid_fullname": "⚠️ Пожалуйста, введите полное имя (минимум 3 символа).",
        "btn_send_phone": "📱 Отправить номер телефона",
        "ask_phone": "📞 Отправьте свой номер телефона, нажав кнопку ниже (или введите вручную):",
        "invalid_phone": "⚠️ Неверный формат номера. Пример: +998901234567\nИли нажмите кнопку ниже.",
        "btn_uzb": "🇺🇿 Узбекистан",
        "ask_region": "🌍 Выберите или введите страну:",
        "btn_tashkent_city": "📍 Город Ташкент",
        "btn_tashkent_region": "📍 Ташкентская область",
        "ask_district": "🏙 Выберите регион или город:",
        "districts": ["Сергели", "Юнусабад", "Чиланзар", "Мирзо-Улугбек", "Яшнабад", "Алмазар"],
        "ask_district_detailed": "🗺 Выберите район:",
        "btn_location_a": "📍 Отправить текущую геопозицию (Точка А)",
        "ask_location_a": "🚚 <b>Точка А:</b> Откуда забирать груз? Отправьте локацию с помощью кнопки ниже:",
        "btn_location_b": "📍 Адрес доставки (Точка Б)",
        "ask_location_b": "🏁 <b>Точка Б:</b> Куда доставить груз? Нажмите кнопку и отправьте локацию:",
        "invalid_location": "⚠️ Пожалуйста, отправьте локацию, используя кнопку.",
        "truck_gazelle": "🚛 Газель (Мебель и крупные грузы)",
        "truck_labo": "🚙 Лабо / Дамас (Мелкие грузы)",
        "truck_isuzu": "🚚 Исузу (Очень крупные переезды)",
        "ask_truck": "📦 Какой тип грузовика вам нужен?",
        "movers_yes": "🙋‍♂️ Да, нужны грузчики",
        "movers_no": "❌ Нет, мы загрузим сами",
        "ask_movers": "💪 Нужны ли вам грузчики для переноски мебели?",
        "btn_no_photo": "⏩ Отправить без фото",
        "ask_photo": "📸 Если возможно, отправьте фото мебели или груза.\nИли нажмите кнопку ниже:",
        "success": "✅ Спасибо! Ваша заявка успешно принята. Наши администраторы скоро свяжутся с вами.",
        "cancel_success": "❌ Заказ отменен. Отправьте /start для начала заново.",
        "cancel_empty": "Сейчас нет активного процесса для отмены.",
        "fallback": "🤖 Отправьте команду /start, чтобы начать оформление заказа."
    }
}

def get_text(lang: str, key: str) -> str:
    if lang not in TRANSLATIONS:
        lang = "uz"
    return TRANSLATIONS[lang].get(key, TRANSLATIONS["uz"].get(key, key))
